[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  framework = "#custom"

[[edge_functions]]
  path = "/*"
  function = "transform"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NETLIFY_USE_YARN = "false"